name: eShopOnWeb Build and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        include-prerelease: true

    - name: Build with dotnet
      run: dotnet build ./eShopOnWeb.sln --configuration Release
    
    - name: Test with dotnet
      run: dotnet test ./eShopOnWeb.sln --configuration Release

    - name: Copy Files
      run: |
        Copy-Item -Path C:\Users\vamshi\actions-runner\coresonant\eShopOnWeb\eShopOnWeb\* -Destination C:\inetpub\wwwroot\publish -Recurse -Force

    - name: Archive Artifact
      uses: actions/upload-artifact@v2
      with:
        name: eshop on web
        path: C:\inetpub\wwwroot\publish

  deploy:
    needs: build
    runs-on: windows-latest
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: eshop on web
        path: C:\artifact

    - name: Deploy with msdeploy
      run: |
        "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe" -source:contentPath="C:\artifact" -verb:sync -dest:contentPath=c:\C:\inetpub\wwwroot\production,computerName=98.70.15.8,userName=vamshi,password=Vamshikrishna@1 -allowUntrusted
